<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>opencast-migration-utils</artifactId>
  <packaging>bundle</packaging>
  <name>Opencast :: migration-utils</name>
  <parent>
    <groupId>org.opencastproject</groupId>
    <artifactId>base</artifactId>
    <version>11-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <properties>
    <opencast.basedir>${project.basedir}/../..</opencast.basedir>
    <checkstyle.skip>false</checkstyle.skip>
  </properties>
  <dependencies>
    <!-- osgi support -->
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>osgi.cmpn</artifactId>
    </dependency>
    <!-- other -->
    <dependency>
      <groupId>jakarta.ws.rs</groupId>
      <artifactId>jakarta.ws.rs-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
    <dependency>
      <groupId>com.entwinemedia.common</groupId>
      <artifactId>functional</artifactId>
    </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
    </dependency>
    <!-- Opencast -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opencastproject</groupId>
      <artifactId>opencast-themes</artifactId>
      <version>11-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.opencastproject</groupId>
      <artifactId>opencast-common</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.opencastproject</groupId>
      <artifactId>opencast-static-file-service-api</artifactId>
      <version>11-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.opencastproject</groupId>
      <artifactId>opencast-index-service</artifactId>
      <version>11-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.opencastproject</groupId>
      <artifactId>opencast-admin-ui</artifactId>
      <version>11-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.opencastproject</groupId>
      <artifactId>opencast-elasticsearch-api</artifactId>
      <version>11-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.opencastproject</groupId>
      <artifactId>opencast-elasticsearch-index</artifactId>
      <version>11-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <ignoredUnusedDeclaredDependencies>
            <!-- runtime tests -->
            <ignoredUnusedDeclaredDependency>com.sun.jersey:jersey-bundle</ignoredUnusedDeclaredDependency>
          </ignoredUnusedDeclaredDependencies>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
            <Build-Number>${buildNumber}</Build-Number>
            <Import-Package>
              javax.ws.rs;version=2.0.1,
              javax.ws.rs.core;version=2.0.1,
              *
            </Import-Package>
            <Export-Package>
              org.opencastproject.migration.utils;version=${project.version},
            </Export-Package>
            <!-- Remove once the Admin UI backend uses OSGi annotations and generates capabilities -->
            <_dsannotations-options>norequirements</_dsannotations-options>
          </instructions>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
