list.name=FACULTIES

list.translatable=false

DF_GERICHTSMEDIZIN=Diagnostik- & Forschungsinstitut für Gerichtliche Medizin
DF_HUMANGENETIK=Diagnostik- & Forschungsinstitut für Humangenetik
DF_HYGIENE=Diagnostik- & Forschungsinstitut für Hygiene, Mikrobiologie und Umweltmedizin
DF_BIOMEDIZIN=Diagnostik- & Forschungsinstitut für Molekulare BioMedizin
DF_PATHOLOGIE=Diagnostik- & Forschungsinstitut für Pathologie

BUERO=Büro des Vizerektors für Studium und Lehre
ETHIK=Ethikkommission
GF_ZENTRUM=Gottfried Schatz Forschungszentrum (für zelluläre Signaltransduktion, Stoffwechsel und Altern)
DOKT=Doktoratsstudien
P2P=P2P - Peer 2 Peer

I_ALLGEMEIN=Institut für Allgemeinmedizin u. evidenzbasierte Versorgungsforschung
I_MEDINFO=Institut für Medizinische Informatik, Statistik und Dokumentation
I_PFLEGE=Institut für Pflegewissenschaft
I_SOZIALMED=Institut für Sozialmedizin und Epidemiologie

KA_TRANSPLANTATION=Klinische Abteilung für Allgemein-, Viszeral- und Transplantationschirurgie
KA_HNO=Klinische Abteilung für allgemeine HNO
KA_PAEDIATRIE=Klinische Abteilung für allgemeine Pädiatrie
KA_RADDIAGNOSTIK=Klinische Abteilung für allgemeine radiologische Diagnostik
KA_ANEASTHIOSOLOGIE1=Klinische Abteilung für Anästhesiologie und Intensivmedizin 1
KA_ANEASTHESIOLOGIE2=Klinische Abteilung für Anästhesiologie und Intensivmedizin 2
KA_ANGIOLOGIE=Klinische Abteilung für Angiologie
KA_ENDOKRINOLOGIE=Klinische Abteilung für Endokrinologie u. Diabetologie
KA_GASTROENTEROLOGIE=Klinische Abteilung für Gastroenterologie u. Hepatologie
KA_GEBURTSHILFE=Klinische Abteilung für Geburtshilfe
KA_GEFAESSCHIRURGIE=Klinische Abteilung für Gefäßchirurgie
KA_GYNAEKOLOGIE=Klinische Abteilung für Gynäkologie
KA_HAEMATOLOGIE=Klinische Abteilung für Hämatologie
KA_HERZCHIRURGIE=Klinische Abteilung für Herzchirurgie
KA_INFEKTIOLOGIE=Klinische Abteilung für Infektiologie
KA_KARDIOLOGIE=Klinische Abteilung für Kardiologie
KA_JUGENDPSYCHIATRIE=Klinische Abteilung für Kinder- und Jugendpsychiatrie und Psychotherapeutische Medizin 
KA_KINDERRADIOLOGIE=Klinische Abteilung für Kinderradiologie
KA_PSYCHOLOGIE=Klinische Abteilung für Medizinische Psychologie, Psychosomatik und Psychotherapie
KA_LABORDIAGNOSTIK=Klinische Abteilung für Medizinische und Chemische Labordiagnostik  (KIMCL)
KA_KIEFERCHIRURGIE=Klinische Abteilung für Mund-, Kiefer- und Gesichtschirurgie
KA_NEONATALOGIE=Klinische Abteilung für Neonatologie
KA_NEPHROLOGIE=Klinische Abteilung für Nephrologie
KA_NEURORADIOLOGIE=Klinische Abteilung für Neuroradiologie, vaskuläre u. interventionelle Radiologie
KA_NUKLEARMED=Klinische Abteilung für Nuklearmedizin
KA_ONKOLOGIE=Klinische Abteilung für Onkologie
KA_KIEFERORTHO=Klinische Abteilung für Orale Chirurgie u. Kieferorthopädie
KA_PAEDONKO=Klinische Abteilung für pädiatrische Hämato-Onkologie
KA_KARDIOLOGIE=Klinische Abteilung für pädiatrische Kardiologie
KA_PULMONOLOGIE=Klinische Abteilung für pädiatrische Pulmonologie und Allergologie
KA_PHONIATRIE=Klinische Abteilung für Phoniatrie
KA_PLASTIK=Klinische Abteilung für plastische, ästhetische u. rekonstruktive Chirurgie
KA_PSYCHIATRIE=Klinische Abteilung für Psychiatrie und Psychotherapeutische Medizin
KA_PULMOLOGIE=Klinische Abteilung für Pulmologie
KA_RHEUMATOLOGIE=Klinische Abteilung für Rheumatologie u. Immunologie
KA_HYPERBARECHIRURGIE=Klinische Abteilung für Thorax- u. hyperbare Chirurgie
KA_PARODONTOLOGIE=Klinische Abteilung für Zahnerhaltung, Parodontologie u. Zahnersatzkunde

L_IMMUNOLOGIE=Lehrstuhl für Immunologie
L_ANATOMIE=Lehrstuhl für makroskopische und klinische Anatomie 
L_MEDCHEMIE=Lehrstuhl für Medizinische Chemie
L_BIOPHYSIK=Lehrstuhl für Medizinische Physik und Biophysik
L_BIOCHEMIE=Lehrstuhl für Molekularbiologie & Biochemie
L_PHARMAKOLOGIE=Lehrstuhl für Pharmakologie
L_PHYSIOLOGIE=Lehrstuhl für Physiologie & Pathophysiologie
L_ZELLBIOLOGIE=Lehrstuhl für Zellbiologie, Histologie und Embryologie

LB_LUNGE=Ludwig Boltzmann Institut für Lungengefäßforschung
OL_IMMUNOLOGIE=Otto Loewi Forschungszentrum für Gefäßbiologie, Immunologie und Entzündung

UK_AUGENKLINIK=Universitäts-Augenklinik
UK_INTENSIV=Universitätsklinik für Anästhesiologie u. Intensivmedizin
UK_TRANSFUSION=Universitätsklinik für Blutgruppenserologie u. Transfusionsmedizin
UK_CHIRURGIE=Universitätsklinik für Chirurgie
UK_DERMATOLOGIE=Universitätsklinik für Dermatologie u. Venerologie
UK_FRAUENHEILKUNDE=Universitätsklinik für Frauenheilkunde u. Geburtshilfe
UK_HNO=Universitätsklinik für Hals-, Nasen- und Ohrenheilkunde
UK_INNERE=Universitätsklinik für Innere Medizin
UK_JUGENDCHIRURGIE=Universitätsklinik für Kinder- u. Jugendchirurgie
UK_JUGENDHEILKUNDE=Universitätsklinik für Kinder- und Jugendheilkunde
UK_NEUROCHIRURGIE=Universitätsklinik für Neurochirurgie
UK_NEUROLOGIE=Universitätsklinik für Neurologie
UK_TRAUMATOLOGIE=Universitätsklinik für Orthopädie und Traumatologie
UK_PSYCIATRIE=Universitätsklinik für Psychiatrie, Psychosomatik und Psychotherapie
UK_RADIOLOGIE=Universitätsklinik für Radiologie
UK_RADIOONKOLOGIE=Universitätsklinik für Strahlentherapie-Radioonkologie
UK_UROLOGIE=Universitätsklinik für Urologie
UK_ZAHNEDIZIN=Universitätsklinik für Zahnmedizin und Mundgesundheit
